---
abstract: "All about Japanese pop star \"Morning Musume\""
author:
  - 'Kentaro Kuribayashi, <kentarok@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.36
configure_requires:
  ExtUtils::MakeMaker: 6.36
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: mit
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Acme-MorningMusume
no_index:
  directory:
    - inc
    - t
requires:
  Class::Accessor: 0
  Date::Simple: 0
  WWW::Google::Images: 0
resources:
  license: http://opensource.org/licenses/mit-license.php
version: 0.15
