# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Acme-MorningMusume
version:      0.10
version_from: lib/Acme/MorningMusume.pm
installdirs:  site
requires:
    Class::Accessor:               0
    Date::Simple:                  0
    WWW::Google::Images:           0.6.1

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30_01
