--- #YAML:1.0
name:                Acme-MorningMusume
version:             0.08
abstract:            ~
license:             ~
generated_by:        ExtUtils::MakeMaker version 6.31
distribution_type:   module
requires:     
    Class::Accessor:               0
    Date::Simple:                  0
    WWW::Google::Images:           0.6.1
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
